### ISSUE TITLE
Load postal codes as boundaries/polygons

### ISSUE THREAD

**Issue by pierDipi** [agile-lab-dev/GIS.Lib#72]
# Problem statement

Postal codes are not single points, a city might have multiple postal codes and we have to load them as polygons.

# Proposed solution

Load postal codes as boundaries (polygon) like cities or regions.

**Comment by andr3a87** [comment]
[banchedati-cap-zone-demo-database.zip](https://github.com/agile-lab-dev/GIS.Lib/files/6785548/banchedati-cap-zone-demo-database.zip)
